// Research starting points only. Prices, durations and verification dates are
// intentionally absent until evidence is reviewed and published through admin.
export const seedCatalog = [
      {
        id: 'adobe-express',
        name: 'Adobe Express Premium',
        categories: ['design', 'family'],
        facets: ['software trial', 'design'],
        description: 'Design, short video, quick social assets, cards, school flyers, and invitations.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://express.adobe.com/sp/premium',
        goal: 'Create three useful family or social designs before the decision date.'
      },
      {
        id: 'canva-pro',
        name: 'Canva Pro',
        categories: ['design', 'productivity'],
        facets: ['software trial', 'design'],
        description: 'Templates, brand kit, background remover, content planner, and collaboration.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.canva.com/pro/',
        goal: 'Build a reusable template set and decide if it replaces an existing design workflow.'
      },
      {
        id: 'figma-professional',
        name: 'Figma Professional',
        categories: ['design', 'devtools'],
        facets: ['software trial', 'design'],
        description: 'Collaborative design files, shared libraries, and team workspaces.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.figma.com/pricing/',
        goal: 'Prototype one real app screen and test whether collaboration features matter.'
      },
      {
        id: 'notion-plus',
        name: 'Notion Plus',
        categories: ['productivity', 'family', 'learning'],
        facets: ['software trial', 'planning'],
        description: 'Personal wiki, project docs, database views, and shared planning spaces.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.notion.com/pricing',
        goal: 'Run one household or project dashboard for two weeks.'
      },
      {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        categories: ['devtools', 'productivity'],
        facets: ['software trial', 'coding tool'],
        description: 'AI coding assistance in common editors and GitHub workflows.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://github.com/features/copilot',
        goal: 'Use it on one contained coding project and log whether it saves time.'
      },
      {
        id: 'linear',
        name: 'Linear',
        categories: ['productivity', 'devtools'],
        facets: ['software trial', 'planning'],
        description: 'Issue tracking, cycles, project planning, and lightweight engineering workflows.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://linear.app/pricing',
        goal: 'Track one side project with issues, cycles, and a weekly review.'
      },
      {
        id: 'masterclass',
        name: 'MasterClass Membership',
        categories: ['learning', 'family', 'home'],
        facets: ['streaming shows', 'learning'],
        description: 'Structured classes for cooking, writing, music, business, and lifestyle learning.',
        source: 'community',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.masterclass.com/checkout',
        goal: 'Complete one short class module and verify plan terms before the guarantee window ends.'
      },
      {
        id: 'skillshare',
        name: 'Skillshare',
        categories: ['learning', 'design', 'home'],
        facets: ['learning', 'software trial'],
        description: 'Creative, business, and maker classes with practical project formats.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.skillshare.com/en/membership',
        goal: 'Finish one project-based class and create a visible output.'
      },
      {
        id: 'audible-standard',
        name: 'Audible Standard',
        categories: ['learning', 'shows'],
        facets: ['audiobooks', 'podcasts'],
        description: 'Audiobook and podcast membership candidate for testing commute, walk, and bedtime listening.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.audible.com/ep/free-trial?language=en_US',
        goal: 'Finish one audiobook or replace one paid podcast/audiobook purchase before renewal.'
      },
      {
        id: 'kindle-unlimited',
        name: 'Kindle Unlimited',
        categories: ['learning', 'family'],
        facets: ['ebooks', 'books', 'reading'],
        description: 'Digital reading membership candidate for ebooks, magazines, comics, and some audiobooks.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.amazon.com/kindle-dbs/hz/subscribe/ku/',
        goal: 'Read enough from the included catalog to decide if it replaces individual book purchases.'
      },
      {
        id: 'headspace',
        name: 'Headspace',
        categories: ['health', 'family'],
        facets: ['wellness', 'meditation'],
        description: 'Guided meditation, sleep support, focus, and family-friendly mindfulness content.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.headspace.com/subscriptions',
        goal: 'Use it five times and decide if it improves sleep or focus.'
      },
      {
        id: 'ynab',
        name: 'YNAB',
        categories: ['finance', 'family'],
        facets: ['software trial', 'budgeting'],
        description: 'Budgeting workflow for planning dollars, reducing surprises, and shared finances.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.ynab.com/pricing',
        goal: 'Build one monthly budget and run a weekly money check-in.'
      },
      {
        id: 'hulu',
        name: 'Hulu',
        categories: ['shows', 'family'],
        facets: ['streaming shows', 'movies'],
        description: 'Streaming plan candidate for testing TV, movies, and family entertainment needs.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.hulu.com/welcome',
        goal: 'Watch the shows you actually wanted and decide if the catalog is worth keeping.'
      },
      {
        id: 'youtube-tv',
        name: 'YouTube TV',
        categories: ['shows', 'family'],
        facets: ['live sports', 'live tv', 'streaming shows'],
        description: 'Live TV streaming candidate for sports, news, and cable replacement testing.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://tv.youtube.com/',
        goal: 'Test whether it can replace cable or a sports package before conversion.'
      },
      {
        id: 'hellofresh',
        name: 'HelloFresh',
        categories: ['meals', 'delivery', 'family'],
        facets: ['meal kit', 'dinner'],
        description: 'Meal-kit candidate for comparing dinner cost, prep time, and household fit.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.hellofresh.com/',
        goal: 'Try two weeks of meals and compare cost, waste, and time saved.'
      },
      {
        id: 'instacart-plus',
        name: 'Instacart+',
        categories: ['delivery', 'meals', 'family'],
        facets: ['grocery delivery'],
        description: 'Grocery delivery membership candidate for testing saved trips and fees.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.instacart.com/instacart-plus',
        goal: 'Place two real grocery orders and compare fees, substitutions, and time saved.'
      },
      {
        id: 'doordash-dashpass',
        name: 'DashPass',
        categories: ['delivery', 'meals'],
        facets: ['restaurant delivery', 'takeout'],
        description: 'Delivery membership candidate for testing whether order frequency justifies fees.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.doordash.com/dashpass/',
        goal: 'Track two to four orders and calculate whether fee savings beat the monthly cost.'
      },
      {
        id: 'thumbtack',
        name: 'Thumbtack',
        categories: ['services', 'home'],
        facets: ['local quotes'],
        description: 'Local service marketplace candidate for comparing quotes before hiring.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.thumbtack.com/',
        goal: 'Collect three quotes and compare price, availability, and confidence.'
      },
      {
        id: 'cloudflare-workers',
        name: 'Cloudflare Workers',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'app hosting', 'serverless'],
        description: 'Serverless app hosting with a useful free tier for APIs, workers, static assets, and edge experiments.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.cloudflare.com/products/workers/',
        goal: 'Deploy one small API or app and confirm request, CPU, storage, and custom-domain limits.'
      },
      {
        id: 'vercel-hobby',
        name: 'Vercel Hobby',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'app hosting', 'nextjs hosting'],
        description: 'Frontend and full-stack app hosting for Next.js and web projects with a hobby tier.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://vercel.com/pricing',
        goal: 'Deploy one app, test preview deployments, bandwidth limits, and whether usage stays within hobby rules.'
      },
      {
        id: 'netlify-free',
        name: 'Netlify Free',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'app hosting'],
        description: 'Static and Jamstack hosting with builds, deploy previews, forms, and serverless functions.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.netlify.com/pricing/',
        goal: 'Host one static app and verify build, bandwidth, function, and team limits before relying on it.'
      },
      {
        id: 'render-free',
        name: 'Render Free',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'app hosting'],
        description: 'Cloud hosting for web services, static sites, databases, and background workers with free/trial-friendly tiers.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://render.com/pricing',
        goal: 'Deploy one small service and measure cold start, sleep behavior, and monthly cost risk.'
      },
      {
        id: 'oracle-cloud-free',
        name: 'Oracle Cloud Free Tier',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'compute', 'free tier'],
        description: 'Cloud free tier with always-free resources and trial credits for broader cloud services.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://www.oracle.com/cloud/free/',
        goal: 'Check whether always-free compute is available in your region and document upgrade/billing risk.'
      },
      {
        id: 'aws-free-tier',
        name: 'AWS Free Tier',
        categories: ['cloudinfra', 'devtools'],
        facets: ['free cloud hosting', 'compute', 'free tier'],
        description: 'Broad cloud free tier for compute, storage, databases, and serverless services.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://aws.amazon.com/free/',
        goal: 'Identify the exact services needed and set budget alerts before deploying anything persistent.'
      },
      {
        id: 'google-cloud-free',
        name: 'Google Cloud Free',
        categories: ['cloudinfra', 'aiapis', 'devtools'],
        facets: ['free cloud hosting', 'free ai api', 'free tier'],
        description: 'Cloud free program and credits for trying infrastructure, serverless, databases, and AI-related services.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://cloud.google.com/free',
        goal: 'Use only the services needed for one app and confirm what happens after credits or limits expire.'
      },
      {
        id: 'gemini-api-free',
        name: 'Google Gemini API',
        categories: ['aiapis', 'devtools'],
        facets: ['free ai api', 'model api'],
        description: 'Model API access through Google AI Studio / Gemini API with documented free-tier rate limits.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://ai.google.dev/gemini-api/docs/rate-limits',
        goal: 'Connect one local harness and confirm daily/minute quotas, model quality, and billing requirements.'
      },
      {
        id: 'groq-api-free',
        name: 'Groq API',
        categories: ['aiapis', 'devtools'],
        facets: ['free ai api', 'model api'],
        description: 'Fast hosted model API with documented rate limits for experimentation and agent harness testing.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://console.groq.com/docs/rate-limits',
        goal: 'Connect one coding or chat harness and measure latency, reliability, and model fit.'
      },
      {
        id: 'openrouter-free-models',
        name: 'OpenRouter Free Models',
        categories: ['aiapis', 'harnesses', 'devtools'],
        facets: ['free ai api', 'model router'],
        description: 'Model-router API with a filterable list of free models that many local harnesses can use.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://openrouter.ai/models?max_price=0',
        goal: 'Connect one OpenAI-compatible harness and compare two free models on your actual tasks.'
      },
      {
        id: 'cloudflare-workers-ai',
        name: 'Cloudflare Workers AI',
        categories: ['aiapis', 'cloudinfra', 'devtools'],
        facets: ['free ai api', 'free cloud hosting', 'model api'],
        description: 'AI inference APIs colocated with Cloudflare Workers for lightweight agent and app experiments.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://developers.cloudflare.com/workers-ai/platform/pricing/',
        goal: 'Try one edge-hosted AI feature and confirm free allocation, latency, and model coverage.'
      },
      {
        id: 'github-models',
        name: 'GitHub Models',
        categories: ['aiapis', 'devtools'],
        facets: ['free ai api', 'model api', 'coding tool'],
        description: 'GitHub-hosted model playground and API surface for trying models in developer workflows.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://docs.github.com/en/github-models',
        goal: 'Test one model from a dev workflow and confirm rate limits and API compatibility.'
      },
      {
        id: 'aider',
        name: 'Aider',
        categories: ['harnesses', 'devtools'],
        facets: ['agent harness', 'coding tool'],
        description: 'Open-source AI pair-programming harness that runs in your terminal and edits local repos.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://aider.chat/',
        goal: 'Connect it to one local or API model and try a contained patch with tests.'
      },
      {
        id: 'opencode',
        name: 'OpenCode',
        categories: ['harnesses', 'devtools'],
        facets: ['agent harness', 'coding tool'],
        description: 'Terminal-based AI coding agent/harness for connecting models to local development workflows.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://opencode.ai/',
        goal: 'Run it on a small repo and compare workflow quality against your current coding setup.'
      },
      {
        id: 'continue',
        name: 'Continue',
        categories: ['harnesses', 'devtools'],
        facets: ['agent harness', 'coding tool'],
        description: 'Open-source AI code assistant extension and harness for local or hosted models.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://continue.dev/',
        goal: 'Connect a local model and a free API model, then compare code-editing usefulness.'
      },
      {
        id: 'openhands',
        name: 'OpenHands',
        categories: ['harnesses', 'devtools'],
        facets: ['agent harness', 'coding tool'],
        description: 'Open-source software development agent platform for autonomous coding workflows.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://docs.openhands.dev/overview/introduction',
        goal: 'Run one sandboxed coding task and document setup complexity, cost, and patch quality.'
      },
      {
        id: 'litellm',
        name: 'LiteLLM',
        categories: ['harnesses', 'aiapis', 'devtools'],
        facets: ['model router'],
        description: 'Model gateway/router for connecting harnesses to many OpenAI-compatible and hosted model APIs.',
        source: 'official',
        eligibility: 'Not confirmed — review current provider terms.',
        url: 'https://docs.litellm.ai/docs/',
        goal: 'Route one harness through two model providers and confirm fallback, logging, and cost controls.'
      }
    ];
