import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { doc, setDoc } from 'firebase/firestore';
const base = 'http://127.0.0.1:4177';
const env = await initializeTestEnvironment({projectId:'demo-trywise',firestore:{host:'127.0.0.1',port:8080,rules:readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});
const browser = await chromium.launch();
async function google(page,email){
  await page.evaluate(async email=>{
    const {getApp}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');
    const {getAuth,GoogleAuthProvider,signInWithCredential}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');
    if(getApp().options.projectId!=='demo-trywise')throw new Error('Emulator only');
    const encode=v=>btoa(JSON.stringify(v)).replaceAll('=','').replaceAll('+','-').replaceAll('/','_');
    const token=`${encode({alg:'none',typ:'JWT'})}.${encode({sub:email,email,email_verified:true,name:'Emulator tester',iss:'https://accounts.google.com',aud:'demo-client',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600})}.`;
    await signInWithCredential(getAuth(),GoogleAuthProvider.credential(token));
  },email);
}
try{
  await env.clearFirestore();
  await env.withSecurityRulesDisabled(async ctx=>{
    await setDoc(doc(ctx.firestore(),'candidates','browser-candidate'),{id:'browser-candidate',title:'Browser approved offer',url:'https://example.com/trial',observedAt:new Date().toISOString(),evidence:['An emulator-only trial.'],status:'pending_review'});
    await setDoc(doc(ctx.firestore(),'catalog','github-copilot'),{id:'github-copilot',status:'published',revision:1,name:'Existing published name',description:'Previously approved fixture',category:'devtools',url:'https://example.com/pricing',offerType:'free_tier',trialDays:0,reviewDays:14,monthlyValue:0,upfrontCost:0,currency:'USD',priceDetails:'Limited free usage',eligibility:'Eligible accounts',region:'United States',cancellation:'Cancel in account settings',goal:'Try a project',expiresAt:null});
    const quote='Demo Free plan with limited usage. <img src=x onerror=alert(1)>';
    const field=value=>({value,quote});
    await setDoc(doc(ctx.firestore(),'candidates','raw-candidate'),{id:'raw-candidate',title:'Raw pricing evidence',sourceId:'github-copilot-plans',url:'https://example.com/pricing',observedAt:new Date(Date.now()-1000).toISOString()});
    await setDoc(doc(ctx.firestore(),'candidates','draft-candidate'),{id:'draft-candidate',draftParentId:'raw-candidate',title:'AI draft browser fixture',sourceId:'github-copilot-plans',url:'https://example.com/pricing',evidenceUrl:'https://example.com/pricing',observedAt:new Date().toISOString(),status:'pending_review',draftStatus:'ready',aiDraft:{schemaVersion:1,status:'unverified',provider:'ollama-local',model:'emulator-local',sourceUrl:'https://example.com/pricing',fields:{name:field('Draft Free name'),description:field('AI draft description'),offerType:field('free_tier'),monthlyValue:field(0),trialDays:field(0),confirmed:field(true),url:field('https://evil.example'),notes:field('overwrite private notes')}}});
  });
  const context=await browser.newContext();
  const admin=await context.newPage();
  const visitor=await (await browser.newContext()).newPage();
  const errors=[];
  for(const page of [admin,visitor]){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());}
  await visitor.goto(`${base}/?emulator=1`);
  await visitor.locator('[data-add-catalog="hellofresh"]').click();
  const savedBefore=await visitor.evaluate(()=>localStorage.getItem('trywise-state-v2'));
  await admin.goto(`${base}/admin.html?emulator=1`);
  await admin.locator('#signIn').waitFor({state:'visible'});
  await admin.waitForFunction(()=>!document.getElementById('signIn').disabled);
  await google(admin,'sohan2405@gmail.com');
  await admin.locator('#workspace').waitFor({state:'visible'});
  await admin.getByRole('button',{name:/AI draft browser fixture — needs review/}).click();
  assert.equal(await admin.locator('#queue > .offer-group').count(),2,'Related versions form a single queue group');
  assert.equal(await admin.locator('#queue details[open]').count(),0,'History is collapsed initially');
  await admin.locator('#queue summary').click();
  await admin.getByRole('button',{name:/History: Raw pricing evidence/}).waitFor({state:'visible'});
  await admin.locator('#queue summary').click();
  await admin.locator('#draftInfo').waitFor({state:'visible'});
  assert.equal(await admin.locator('#name').inputValue(),'Draft Free name','Draft must not be overwritten by current published target');
  assert.equal(await admin.locator('#offerId').inputValue(),'github-copilot');
  assert.notEqual(await admin.locator('#url').inputValue(),'https://evil.example');
  assert.equal(await admin.locator('#monthlyValue').inputValue(),'0');
  for(const key of ['upfrontCost','region','cancellation','priceDetails'])assert.equal(await admin.locator(`#${key}`).inputValue(),'','Unknown fields stay blank');
  assert.equal(await admin.locator('#confirmed').isChecked(),false);
  assert.equal(await admin.locator('#notes').inputValue(),'');
  assert.equal(await admin.locator('#draftInfo img').count(),0,'Model excerpts must be text, not HTML');
  assert.match(await admin.locator('#targetStatus').textContent(),/revision 1/);
  await admin.locator('#confirmed').check();
  await admin.getByRole('button',{name:'Use AI draft fields',exact:true}).click();
  assert.equal(await admin.locator('#confirmed').isChecked(),false,'Applying a draft resets approval confirmation');
  await admin.setViewportSize({width:390,height:844});
  assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await admin.screenshot({path:'/private/tmp/trywise-ai-draft-mobile.png',fullPage:true});
  await admin.locator('#backToQueue').click();
  await admin.getByRole('button',{name:/Browser approved offer — needs review/}).click();
  await admin.locator('#reviewForm').waitFor({state:'visible'});
  await admin.waitForFunction(()=>document.getElementById('targetStatus').textContent.includes('new public offer'));
  for(const [id,value] of Object.entries({description:'Emulator-only offer description',priceDetails:'$12 per month after a 14-day trial',eligibility:'New customers',region:'United States',cancellation:'Cancel online before renewal',goal:'Test one useful project'}))await admin.locator(`#${id}`).fill(value);
  for(const [id,value] of Object.entries({identityProvider:'example',identityProduct:'browser-offer',identityPlan:'standard',identityRegion:'us',identityScope:'general'}))await admin.locator(`#${id}`).fill(value);
  await admin.locator('#category').selectOption('devtools');
  await admin.locator('#offerType').selectOption('trial');
  await admin.locator('#trialDays').fill('14');
  await admin.locator('#monthlyValue').fill('12');
  await admin.locator('#confirmed').check();
  await admin.setViewportSize({width:390,height:844});
  assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await admin.screenshot({path:'/private/tmp/trywise-admin-mobile.png',fullPage:true});
  await admin.locator('#publish').click();
  await admin.waitForFunction(()=>document.getElementById('message').textContent.startsWith('Published.'));
  await visitor.locator('#searchInput').fill('Browser approved offer');
  await visitor.locator('[data-add-catalog="browser-approved-offer"]').waitFor();
  assert.equal(await visitor.evaluate(()=>localStorage.getItem('trywise-state-v2')),savedBefore,'Publishing must not modify a saved plan');
  await admin.locator('#reviewFilter').selectOption('pending');
  await admin.waitForFunction(()=>document.querySelectorAll('#queue > .offer-group').length===1);
  await admin.locator('#reviewFilter').selectOption('all');
  await admin.getByRole('button',{name:/Browser approved offer — approved/}).click();
  await admin.locator('#offerId').fill('accidental-duplicate');
  await admin.getByRole('button',{name:'Update existing offer: browser-approved-offer',exact:true}).click();
  await admin.waitForFunction(()=>document.getElementById('targetStatus').textContent.includes('revision 1'));
  assert.equal(await admin.locator('#offerId').inputValue(),'browser-approved-offer');
  assert.equal(await admin.locator('#identityRegion').inputValue(),'us');
  assert.equal(await admin.locator('#confirmed').isChecked(),false);
  await admin.locator('#cancel').click();
  await admin.locator('#queueType').selectOption('published');
  await admin.getByRole('button',{name:'Withdraw Browser approved offer',exact:true}).click();
  await visitor.locator('[data-add-catalog="browser-approved-offer"]').waitFor({state:'detached'});
  assert.equal(await visitor.evaluate(()=>localStorage.getItem('trywise-state-v2')),savedBefore);
  await admin.locator('#queueType').selectOption('collected');
  await admin.getByRole('button',{name:/Browser approved offer — approved/}).click();
  await admin.locator('#notes').fill('Rejected in emulator test');
  await admin.locator('#reject').click();
  await admin.waitForFunction(()=>document.getElementById('message').textContent.startsWith('Rejected.'));
  await admin.locator('#queueType').selectOption('seeds');
  await admin.getByRole('button',{name:/Notion Plus — needs review/}).click();
  await admin.waitForFunction(()=>document.getElementById('evidence').textContent.includes('Source audit'));
  assert.match(await admin.locator('#evidence').textContent(),/limited AI trial is not a trial of the whole Plus/);
  await admin.locator('#signOut').click();
  await admin.locator('#workspace').waitFor({state:'hidden'});
  assert.equal(await admin.locator('#evidence').textContent(),'');
  assert.equal(await admin.locator('#draftInfo').textContent(),'');
  await google(admin,'ordinary-tester@example.com');
  await admin.waitForFunction(()=>document.getElementById('identity').textContent.includes('not authorized'));
  assert.equal(await admin.locator('#workspace').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('Admin browser passed: grouped collapsed history, pending filter, duplicate update action, identity fields, audit notes, AI draft safeguards, owner authorization, publication, withdrawal, rejection, mobile layout, sign-out clearing, tester denial, and unchanged saved plans.');
}finally{await browser.close();await env.cleanup();}
